-- =============================================================================
-- 0005 · Vokabular-Seeds (idempotent) — neutrale Keys, DE/EN-Labels.
-- Labels aus der Airtable-Analyse übernommen. Als Migration (nicht seed.sql),
-- damit `supabase db push` sie auf dem Cloud-Projekt anwendet (kein lokaler reset).
-- Hierarchie: study_program.parent = study_field (nach study_field eingefügt).
-- =============================================================================
set search_path = public, extensions;

-- --- Nicht-hierarchische Vokabulare -----------------------------------------
insert into vocab_term (vocabulary, key, label_de, label_en, sort_order) values
  -- occupation_status
  ('occupation_status','dualer-student','Dualer-Student','Dual student',1),
  ('occupation_status','bachelor','Bachelor-Student','Bachelor student',2),
  ('occupation_status','master','Master-Student','Master student',3),
  ('occupation_status','staatsexamen','Staatsexamen-Student','State examination student',4),
  ('occupation_status','postgraduate','Postgradual (MBA, Promotion)','Postgraduate (MBA, PhD)',5),
  ('occupation_status','founder','Founder','Founder',6),
  ('occupation_status','berufstaetig','Berufstätig','Employed',7),
  ('occupation_status','azubi','Azubi','Apprentice',8),
  ('occupation_status','schueler','Schüler','Pupil',9),
  ('occupation_status','auszeit-sonstiges','Auszeit, Sonstiges','Sabbatical, other',10),
  -- work_experience
  ('work_experience','0-1','0-1 Jahre','0-1 years',1),
  ('work_experience','2-3','2-3 Jahre','2-3 years',2),
  ('work_experience','4-5','4-5 Jahre','4-5 years',3),
  ('work_experience','6-7','6-7 Jahre','6-7 years',4),
  ('work_experience','8-9','8-9 Jahre','8-9 years',5),
  ('work_experience','10plus','10+ Jahre','10+ years',6),
  -- career_level
  ('career_level','intern','Intern','Intern',1),
  ('career_level','junior','Junior','Junior',2),
  ('career_level','mid','Mid-Level','Mid-Level',3),
  ('career_level','senior','Senior','Senior',4),
  ('career_level','team-lead','Team Lead','Team Lead',5),
  ('career_level','head-of','Head Of','Head Of',6),
  ('career_level','director','Director','Director',7),
  ('career_level','c-level','C-Level','C-Level',8),
  -- employer_type
  ('employer_type','startup','Startup','Startup',1),
  ('employer_type','kleinunternehmen','Kleinunternehmen','Small business',2),
  ('employer_type','mittelstand','Mittelstand','Mid-sized company',3),
  ('employer_type','corporate','Corporate','Corporate',4),
  ('employer_type','ngo','NGO / Non-Profit / Stiftung','NGO / non-profit / foundation',5),
  ('employer_type','public-uni','Öffentlicher Sektor / Universität','Public sector / university',6),
  ('employer_type','investor-vc','Investor / Family Office / VC','Investor / family office / VC',7),
  ('employer_type','agentur','Agentur','Agency',8),
  ('employer_type','selbststaendig','Selbstständig / Freelancer','Self-employed / freelancer',9),
  ('employer_type','ohne','ohne Arbeitgeber','No employer',10),
  ('employer_type','sonstiges','Sonstiges','Other',11),
  -- study_field (Parent für study_program)
  ('study_field','business','Business, Management & Entrepreneurship','Business, Management & Entrepreneurship',1),
  ('study_field','finance-econ','Finance & Economics','Finance & Economics',2),
  ('study_field','wirtschaftsinformatik','Wirtschaftsinformatik & Informatik','Business Informatics & Computer Science',3),
  ('study_field','wirtschaftsing','Wirtschaftsingenieurwesen & Ingenieurwissenschaften','Industrial & General Engineering',4),
  ('study_field','naturwiss','Naturwissenschaften','Natural Sciences',5),
  ('study_field','marketing-medien','Marketing, Medien & Kommunikation','Marketing, Media & Communication',6),
  ('study_field','sozialwiss-recht','Sozialwissenschaften & Recht','Social Sciences & Law',7),
  ('study_field','medizin-gesundheit','Medizin & Gesundheitswissenschaften','Medicine & Health Sciences',8),
  ('study_field','sonstiges','Sonstiges','Other',9),
  -- interests (14) — Labels sind bereits englisch
  ('interests','finance-banking','Finance & Banking','Finance & Banking',1),
  ('interests','tech-ai','Tech & AI','Tech & AI',2),
  ('interests','strategy-consulting','Strategy & Consulting','Strategy & Consulting',3),
  ('interests','impact-sustainability','Impact & Sustainability','Impact & Sustainability',4),
  ('interests','marketing-brand','Marketing & Brand','Marketing & Brand',5),
  ('interests','leadership-mgmt','Leadership & Management','Leadership & Management',6),
  ('interests','entrepreneurship-scaling','Entrepreneurship & Scaling','Entrepreneurship & Scaling',7),
  ('interests','health-wellbeing','Health & Wellbeing','Health & Wellbeing',8),
  ('interests','sales-growth','Sales & Growth','Sales & Growth',9),
  ('interests','engineering-tech','Engineering & Technology','Engineering & Technology',10),
  ('interests','logistics-operations','Logistics & Operations','Logistics & Operations',11),
  ('interests','psychology-behavior','Psychology & Behavior','Psychology & Behavior',12),
  ('interests','politics-society','Politics & Society','Politics & Society',13),
  ('interests','law-ethics','Law & Ethics','Law & Ethics',14),
  -- interests_founder (10)
  ('interests_founder','fundraising','Fundraising & Investoren','Fundraising & Investors',1),
  ('interests_founder','product-building','Product Building','Product Building',2),
  ('interests_founder','terms-contracts','Terms & Contracts','Terms & Contracts',3),
  ('interests_founder','growth-hacks','Growth Hacks','Growth Hacks',4),
  ('interests_founder','team-culture','Team & Culture','Team & Culture',5),
  ('interests_founder','sales-scaling','Sales & Scaling','Sales & Scaling',6),
  ('interests_founder','ideation-validation','Ideation & Validation','Ideation & Validation',7),
  ('interests_founder','mvp-prototyping','MVP Development & Prototyping','MVP Development & Prototyping',8),
  ('interests_founder','legal-ip-tax','Legal / IP & Tax Basics','Legal / IP & Tax Basics',9),
  ('interests_founder','cofounder-recruiting','Co-Founder Matching & Recruitment','Co-Founder Matching & Recruitment',10),
  -- startup_phase
  ('startup_phase','idee','Konzept/Idee','Concept/Idea',1),
  ('startup_phase','pre-seed','Pre-Seed','Pre-Seed',2),
  ('startup_phase','seed','Seed','Seed',3),
  ('startup_phase','early-stage','Early Stage','Early Stage',4),
  ('startup_phase','scale-up','Scale Up','Scale Up',5),
  ('startup_phase','later-stage','Later Stage','Later Stage',6),
  ('startup_phase','post-exit','Post-Exit','Post-Exit',7),
  -- career_opportunities
  ('career_opportunities','praktikum','Praktikum','Internship',1),
  ('career_opportunities','werkstudium','Werkstudium','Working student',2),
  ('career_opportunities','abschlussarbeit','Abschlussarbeit bei einem Unternehmen','Thesis with a company',3),
  ('career_opportunities','trainee','Trainee','Trainee',4),
  ('career_opportunities','einstieg-vz','Einstiegsjob - Vollzeit','Entry-level - full-time',5),
  ('career_opportunities','senior-vz','Senior - Vollzeit','Senior - full-time',6),
  ('career_opportunities','lead-vz','Team Lead/Manager - Vollzeit','Team lead/manager - full-time',7),
  ('career_opportunities','gruendungsfoerderung','Gründungsförderung / Incubator','Startup funding / incubator',8),
  ('career_opportunities','teilzeit','Teilzeit-Stelle','Part-time position',9),
  ('career_opportunities','nicht-interessiert','Ich bin aktuell nicht interessiert an Jobangeboten','Currently not interested in job offers',10),
  -- self_assessment
  ('self_assessment','top-1','Top 1%','Top 1%',1),
  ('self_assessment','top-10','Top 10%','Top 10%',2),
  ('self_assessment','top-25','Top 25%','Top 25%',3),
  ('self_assessment','top-50','Top 50%','Top 50%',4),
  ('self_assessment','sonstiges','Sonstiges','Other',5),
  ('self_assessment','keine-angabe','Keine Angabe','Prefer not to say',6),
  -- gender
  ('gender','maennlich','Männlich','Male',1),
  ('gender','weiblich','Weiblich','Female',2),
  ('gender','divers','Divers','Diverse',3),
  ('gender','keine-angabe','keine Angabe','Prefer not to say',4),
  -- registration_status
  ('registration_status','applied','Beworben','Applied',1),
  ('registration_status','waitlisted','Warteliste','Waitlisted',2),
  ('registration_status','confirmed','Bestätigt','Confirmed',3),
  ('registration_status','declined','Abgelehnt','Declined',4),
  ('registration_status','no_response','Keine Antwort','No response',5),
  ('registration_status','attended','Teilgenommen','Attended',6),
  ('registration_status','no_show','Nicht erschienen','No show',7),
  -- lifecycle_status
  ('lifecycle_status','lead','Lead','Lead',1),
  ('lifecycle_status','interested','Interessiert','Interested',2),
  ('lifecycle_status','applicant','Bewerber','Applicant',3),
  ('lifecycle_status','participant','Teilnehmer','Participant',4),
  ('lifecycle_status','alumni','Alumni','Alumni',5),
  -- format_tag
  ('format_tag','summit','Summit','Summit',1),
  ('format_tag','academy_hh','Academy Hamburg','Academy Hamburg',2),
  ('format_tag','academy_muc','Academy München','Academy Munich',3),
  ('format_tag','bootcamp_ai','Bootcamp AI','Bootcamp AI',4),
  ('format_tag','club_event','Club Event','Club Event',5),
  ('format_tag','speaker_night','Speaker Night','Speaker Night',6),
  ('format_tag','podcast','Podcast','Podcast',7),
  -- contact_role
  ('contact_role','primary_operations','Primär / Operativ','Primary / operations',1),
  ('contact_role','cc','CC','CC',2),
  ('contact_role','event_app_member','Event-App-Mitglied','Event app member',3),
  ('contact_role','signing','Zeichnungsberechtigt','Signing',4),
  ('contact_role','accounting','Buchhaltung','Accounting',5),
  -- partner_category
  ('partner_category','startup','Startup','Startup',1),
  ('partner_category','talent','Talent','Talent',2),
  -- doc_type
  ('doc_type','offer','Angebot','Offer',1),
  ('doc_type','invoice','Rechnung','Invoice',2),
  ('doc_type','logo_dark','Logo dunkel','Logo dark',3),
  ('doc_type','logo_light','Logo hell','Logo light',4),
  ('doc_type','backdrop','Backdrop','Backdrop',5),
  ('doc_type','other','Sonstiges','Other',6),
  -- ticket_type (neu)
  ('ticket_type','student','Student Pass','Student Pass',1),
  ('ticket_type','talent','Talent Pass','Talent Pass',2),
  ('ticket_type','startup','Startup Pass','Startup Pass',3),
  ('ticket_type','professional','Professional Pass','Professional Pass',4),
  ('ticket_type','investor','Investor Pass','Investor Pass',5),
  ('ticket_type','supporter','Supporter Pass','Supporter Pass',6),
  ('ticket_type','partner','Partner Pass','Partner Pass',7),
  ('ticket_type','speaker','Speaker Pass','Speaker Pass',8),
  ('ticket_type','crew','Crew Pass','Crew Pass',9),
  -- acquisition_channel (neu)
  ('acquisition_channel','instagram','Instagram','Instagram',1),
  ('acquisition_channel','linkedin','LinkedIn','LinkedIn',2),
  ('acquisition_channel','uni-prof','Uni oder Professor','University or professor',3),
  ('acquisition_channel','student-initiative','Studentische Initiative','Student initiative',4),
  ('acquisition_channel','friends-colleagues','Freunde oder Kollegen','Friends or colleagues',5),
  ('acquisition_channel','exhibitors-partners','Aussteller & Partner','Exhibitors & partners',6),
  ('acquisition_channel','past-events','Frühere Events','Past events',7),
  ('acquisition_channel','website-search','Website/Google Suche','Website/Google search',8),
  ('acquisition_channel','social-ads','Social Media Werbung','Social media ads',9),
  ('acquisition_channel','other','Anders','Other',10)
on conflict (vocabulary, key) do update set
  label_de = excluded.label_de, label_en = excluded.label_en,
  sort_order = excluded.sort_order, active = excluded.active,
  parent_vocabulary = excluded.parent_vocabulary, parent_key = excluded.parent_key;

-- --- study_program (hierarchisch: parent = study_field) ---------------------
insert into vocab_term (vocabulary, key, label_de, label_en, sort_order, parent_vocabulary, parent_key) values
  -- business
  ('study_program','business_bwl','BWL & Business Administration','Business Administration',1,'study_field','business'),
  ('study_program','business_intl','International Business & Management','International Business & Management',2,'study_field','business'),
  ('study_program','business_entrepreneurship','Entrepreneurship & Innovation Management','Entrepreneurship & Innovation Management',3,'study_field','business'),
  ('study_program','business_strategy_ops','Strategic & Operations Management','Strategic & Operations Management',4,'study_field','business'),
  ('study_program','business_risk_compliance','Versicherungs-, Risikomanagement & Compliance','Insurance, Risk Management & Compliance',5,'study_field','business'),
  ('study_program','business_impact','Impact & Sustainability Management','Impact & Sustainability Management',6,'study_field','business'),
  ('study_program','business_wipsych','Wirtschaftspsychologie','Business Psychology',7,'study_field','business'),
  ('study_program','business_logistics','Logistik & Supply Chain Management','Logistics & Supply Chain Management',8,'study_field','business'),
  ('study_program','business_sonstiges','Sonstiges','Other',9,'study_field','business'),
  -- finance-econ
  ('study_program','finance_corp','Finance & Corporate Finance','Finance & Corporate Finance',1,'study_field','finance-econ'),
  ('study_program','finance_vwl','VWL & Economics','Economics',2,'study_field','finance-econ'),
  ('study_program','finance_banking','Banking','Banking',3,'study_field','finance-econ'),
  ('study_program','finance_controlling','Controlling','Controlling',4,'study_field','finance-econ'),
  ('study_program','finance_sonstiges','Sonstiges','Other',5,'study_field','finance-econ'),
  -- wirtschaftsinformatik
  ('study_program','winf_wirtschaftsinformatik','Wirtschaftsinformatik','Business Informatics',1,'study_field','wirtschaftsinformatik'),
  ('study_program','winf_informatik','Informatik','Computer Science',2,'study_field','wirtschaftsinformatik'),
  ('study_program','winf_business_analytics','Business Analytics','Business Analytics',3,'study_field','wirtschaftsinformatik'),
  ('study_program','winf_data_science','Data Science, ML & AI','Data Science, ML & AI',4,'study_field','wirtschaftsinformatik'),
  ('study_program','winf_it_mgmt','IT Management & Digital Business','IT Management & Digital Business',5,'study_field','wirtschaftsinformatik'),
  ('study_program','winf_sonstiges','Sonstiges','Other',6,'study_field','wirtschaftsinformatik'),
  -- wirtschaftsing
  ('study_program','wing_wirtschaftsing','Wirtschaftsingenieurwesen','Industrial Engineering',1,'study_field','wirtschaftsing'),
  ('study_program','wing_ingenieurwesen','Ingenieurwesen','Engineering',2,'study_field','wirtschaftsing'),
  ('study_program','wing_maschinenbau','Maschinenbau','Mechanical Engineering',3,'study_field','wirtschaftsing'),
  ('study_program','wing_luftraumfahrt','Luft- & Raumfahrttechnik','Aerospace Engineering',4,'study_field','wirtschaftsing'),
  ('study_program','wing_sonstiges','Sonstiges','Other',5,'study_field','wirtschaftsing'),
  -- naturwiss
  ('study_program','nat_physik','Physik','Physics',1,'study_field','naturwiss'),
  ('study_program','nat_mathematik','Mathematik','Mathematics',2,'study_field','naturwiss'),
  ('study_program','nat_biologie','Biologie','Biology',3,'study_field','naturwiss'),
  ('study_program','nat_chemie','Chemie','Chemistry',4,'study_field','naturwiss'),
  ('study_program','nat_materialwiss','Materialwissenschaften','Materials Science',5,'study_field','naturwiss'),
  ('study_program','nat_astronomie','Astronomie','Astronomy',6,'study_field','naturwiss'),
  ('study_program','nat_sonstiges','Sonstiges','Other',7,'study_field','naturwiss'),
  -- marketing-medien
  ('study_program','mkt_marketing_social','Marketing & Social Media','Marketing & Social Media',1,'study_field','marketing-medien'),
  ('study_program','mkt_brand','Brand Management','Brand Management',2,'study_field','marketing-medien'),
  ('study_program','mkt_pr','PR & Kommunikation','PR & Communication',3,'study_field','marketing-medien'),
  ('study_program','mkt_journalismus','Journalismus','Journalism',4,'study_field','marketing-medien'),
  ('study_program','mkt_design','Design & Grafikdesign','Design & Graphic Design',5,'study_field','marketing-medien'),
  ('study_program','mkt_media_mgmt','Media Management','Media Management',6,'study_field','marketing-medien'),
  ('study_program','mkt_sonstiges','Sonstiges','Other',7,'study_field','marketing-medien'),
  -- sozialwiss-recht
  ('study_program','soz_jura','Jura & Rechtswissenschaften','Law',1,'study_field','sozialwiss-recht'),
  ('study_program','soz_wirtschaftsrecht','Wirtschaftsrecht','Business Law',2,'study_field','sozialwiss-recht'),
  ('study_program','soz_politik','Politikwissenschaften & Internationale Beziehungen','Political Science & International Relations',3,'study_field','sozialwiss-recht'),
  ('study_program','soz_soziologie','Soziologie & Sozialökonomie','Sociology & Socioeconomics',4,'study_field','sozialwiss-recht'),
  ('study_program','soz_geschichte','Geschichte & Wirtschaftsgeschichte','History & Economic History',5,'study_field','sozialwiss-recht'),
  ('study_program','soz_lehramt','Lehramt & Bildungswissenschaften','Teaching & Education',6,'study_field','sozialwiss-recht'),
  ('study_program','soz_social_sciences','Social Sciences','Social Sciences',7,'study_field','sozialwiss-recht'),
  ('study_program','soz_sonstiges','Sonstiges','Other',8,'study_field','sozialwiss-recht'),
  -- medizin-gesundheit
  ('study_program','med_medizin','Medizin','Medicine',1,'study_field','medizin-gesundheit'),
  ('study_program','med_sportmanagement','Sportmanagement','Sports Management',2,'study_field','medizin-gesundheit'),
  ('study_program','med_gesundheitsmgmt','Gesundheitsmanagement','Health Management',3,'study_field','medizin-gesundheit'),
  ('study_program','med_psychologie','Psychologie','Psychology',4,'study_field','medizin-gesundheit'),
  ('study_program','med_pharmazie','Pharmazie','Pharmacy',5,'study_field','medizin-gesundheit'),
  ('study_program','med_sonstiges','Sonstiges','Other',6,'study_field','medizin-gesundheit')
on conflict (vocabulary, key) do update set
  label_de = excluded.label_de, label_en = excluded.label_en,
  sort_order = excluded.sort_order, active = excluded.active,
  parent_vocabulary = excluded.parent_vocabulary, parent_key = excluded.parent_key;
